### PR TITLE
Update eclipse-tm4e repo config

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by fredg02** [comment]
@netomi can you take a look why the otterdog sync check fails?

**Comment by netomi** [comment]
@sebthom the reason the check-sync check was failing is because the setup was not complete yet. Right now, for every PR that got opened to change the configuration, the tool will check if the current configuration is in sync with the live settings. If a drift is detected, something must have gone amiss or somebody changed settings via the Web UI. In order to avoid overriding settings, we have this safe-guard.

I fixed the problems, from now on it should work as expected.

**Review by netomi — APPROVED** [review]

**Pull request merged**
