### PR TITLE
Reenable JS code scan

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by netomi** [comment]
hmm, the default setup for codeql could not be enabled:

image

**Comment by netomi** [comment]
In cases like that it is suggested to disable the default setup and create a workflow to run codeql manually.

**Comment by sebthom** [comment]
I am also confused by the diff-to-live settings result. it does not match the values I am setting. I don't understand what is diffed here.

**Comment by netomi** [comment]
diff-to-live compares the live config to the current config in the main branch. As java-kotlin could not be enabled by GitHub, the setting stays at the values that were there originally.

**Comment by sebthom** [comment]
I now removed the java-kotlin entry. Shouldnt the diff work now?

**Comment by netomi** [comment]
there are 2 different diffs.

One of your changes compared to the main version
And main version to live

The first one shows the changes correctly.
The second one is mainly for us to see if there is a drift so we have to interfere.

**Comment by netomi** [comment]
so default codeql setup is quite error prone, I usually advise against it and prefer custom workflows for it

**Comment by netomi** [comment]
e.g. https://github.com/eclipse-uprotocol/up-java/blob/main/.github/workflows/codeql.yml

**Comment by sebthom** [comment]
@netomi ok will do. thanks!

**Pull request merged**
